//! Build script: under `tournament`, bake the config TOML named by `YORKIE_TOURNAMENT_CONFIG` into compile-time consts; no-op otherwise.

use std::env;
use std::fs;
use std::path::Path;

/// Env var naming the tournament config TOML (relative to crate root); required when `tournament` is on.
const CONFIG_ENV_VAR: &str = "YORKIE_TOURNAMENT_CONFIG";

fn main() {
    // Gate on the feature's Cargo-provided env var. Absent ⇒ no-op (see module docs).
    if env::var_os("CARGO_FEATURE_TOURNAMENT").is_none() {
        return;
    }

    // The feature is on: the developer must name the config TOML. Re-run if it changes.
    println!("cargo:rerun-if-env-changed={CONFIG_ENV_VAR}");
    let config_path = match env::var(CONFIG_ENV_VAR) {
        Ok(path) if !path.is_empty() => path,
        _ => panic!("the `tournament` feature requires {CONFIG_ENV_VAR}=configs/<event>.toml"),
    };

    // Re-run only when the named tournament config changes.
    println!("cargo:rerun-if-changed={config_path}");

    let generated = generate_tournament_consts(&config_path);

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by Cargo for build scripts");
    let dest = Path::new(&out_dir).join("tournament_consts.rs");
    fs::write(&dest, generated).unwrap_or_else(|e| panic!("failed to write generated consts to {}: {e}", dest.display()));
}

/// Parse the tournament TOML at `config_path` and render the generated Rust source (malformed config panics).
fn generate_tournament_consts(config_path: &str) -> String {
    let text = fs::read_to_string(config_path).unwrap_or_else(|e| panic!("failed to read tournament config {config_path}: {e}"));
    let table: toml::Table = text
        .parse()
        .unwrap_or_else(|e| panic!("failed to parse tournament config {config_path} as TOML: {e}"));

    // TOML key -> generated const; i32 for eval/search hot-path (tt_bytes usize), i64/bool for the once-read time-management values.
    let fv_scale = required_i32(&table, "fv_scale", config_path);
    let max_moves_to_draw = required_i32(&table, "max_moves_to_draw", config_path);
    let draw_contempt = required_i32(&table, "draw_contempt", config_path);
    let tt_bytes = required_usize(&table, "tt_bytes", config_path);
    let move_overhead = required_i64(&table, "move_overhead", config_path);
    let timeout_safety_margin = required_i64(&table, "timeout_safety_margin", config_path);
    let minimum_thinking_time = required_i64(&table, "minimum_thinking_time", config_path);
    let opening_time_weight = required_i64(&table, "opening_time_weight", config_path);
    let byoyomi_margin = required_i64(&table, "byoyomi_margin", config_path);
    let usi_ponder = required_bool(&table, "usi_ponder", config_path);

    format!(
        "// @generated by build.rs from {config_path} — do not edit.\n\
         /// NNUE evaluation scale baked from the tournament config (eval hot path).\n\
         pub const FV_SCALE: i32 = {fv_scale};\n\
         /// Maximum-moves draw horizon (game plies) baked from the tournament config.\n\
         pub const MAX_MOVES_TO_DRAW: i32 = {max_moves_to_draw};\n\
         /// Per-side draw contempt (Value units) baked from the tournament config; Black to\n\
         /// move scores a draw as -DRAW_CONTEMPT, White as +DRAW_CONTEMPT.\n\
         pub const DRAW_CONTEMPT: i32 = {draw_contempt};\n\
         /// Transposition-table size in BYTES baked from the tournament config; the TT cluster\n\
         /// count is derived from this at compile time (see `tt.rs`).\n\
         pub const TT_BYTES: usize = {tt_bytes};\n\
         /// Per-move communication/round-trip overhead (ms) baked from the tournament config;\n\
         /// read at think-start by `timeman` (`Move_Overhead`).\n\
         pub const MOVE_OVERHEAD: i64 = {move_overhead};\n\
         /// Near-deadline safety cushion (ms) baked from the tournament config; the low-time cap\n\
         /// in `timeman` (`Timeout_Safety_Margin`).\n\
         pub const TIMEOUT_SAFETY_MARGIN: i64 = {timeout_safety_margin};\n\
         /// Floor on the committed think time (ms) baked from the tournament config\n\
         /// (`Minimum_Thinking_Time`).\n\
         pub const MINIMUM_THINKING_TIME: i64 = {minimum_thinking_time};\n\
         /// Opening time-allocation weight (percent) baked from the tournament config\n\
         /// (`Opening_Time_Weight`).\n\
         pub const OPENING_TIME_WEIGHT: i64 = {opening_time_weight};\n\
         /// Byoyomi safety margin (ms) baked from the tournament config; subtracted off the\n\
         /// byoyomi period during `go` parsing (`Byoyomi_Margin`).\n\
         pub const BYOYOMI_MARGIN: i64 = {byoyomi_margin};\n\
         /// Whether to emit a USI `ponder` move after `bestmove`, baked from the tournament\n\
         /// config (`USI_Ponder`).\n\
         pub const USI_PONDER: bool = {usi_ponder};\n",
    )
}

/// Fetch an integer key that must be present and fit in `i32`.
fn required_i32(table: &toml::Table, key: &str, config_path: &str) -> i32 {
    let value = table
        .get(key)
        .unwrap_or_else(|| panic!("tournament config {config_path} is missing required key `{key}`"));
    let n = value
        .as_integer()
        .unwrap_or_else(|| panic!("tournament config {config_path} key `{key}` must be an integer, got {value}"));
    i32::try_from(n).unwrap_or_else(|_| panic!("tournament config {config_path} key `{key}` = {n} does not fit in i32"))
}

/// Fetch an integer key that must be present and fit in `usize` (non-negative).
fn required_usize(table: &toml::Table, key: &str, config_path: &str) -> usize {
    let value = table
        .get(key)
        .unwrap_or_else(|| panic!("tournament config {config_path} is missing required key `{key}`"));
    let n = value
        .as_integer()
        .unwrap_or_else(|| panic!("tournament config {config_path} key `{key}` must be an integer, got {value}"));
    usize::try_from(n).unwrap_or_else(|_| panic!("tournament config {config_path} key `{key}` = {n} does not fit in usize"))
}

/// Fetch an integer key that must be present and of TOML integer type (already `i64`-wide).
fn required_i64(table: &toml::Table, key: &str, config_path: &str) -> i64 {
    let value = table
        .get(key)
        .unwrap_or_else(|| panic!("tournament config {config_path} is missing required key `{key}`"));
    value
        .as_integer()
        .unwrap_or_else(|| panic!("tournament config {config_path} key `{key}` must be an integer, got {value}"))
}

/// Fetch a boolean key that must be present and of TOML boolean type.
fn required_bool(table: &toml::Table, key: &str, config_path: &str) -> bool {
    let value = table
        .get(key)
        .unwrap_or_else(|| panic!("tournament config {config_path} is missing required key `{key}`"));
    value
        .as_bool()
        .unwrap_or_else(|| panic!("tournament config {config_path} key `{key}` must be a boolean, got {value}"))
}
