//! Build script: under the `tournament` feature, bake the config TOML named by
//! `YORKIE_TOURNAMENT_CONFIG` into compile-time consts (`$OUT_DIR/tournament_consts.rs`); no-op otherwise.

use std::env;
use std::fs;
use std::path::Path;

/// Env var naming the tournament config TOML (relative to crate root); required when `tournament` is on.
const CONFIG_ENV_VAR: &str = "YORKIE_TOURNAMENT_CONFIG";

fn main() {
    // Gate on the feature's Cargo-provided env var. Absent ⇒ no-op (see module docs).
    if env::var_os("CARGO_FEATURE_TOURNAMENT").is_none() {
        return;
    }

    // The feature is on: the developer must name the config TOML. Re-run if it changes.
    println!("cargo:rerun-if-env-changed={CONFIG_ENV_VAR}");
    let config_path = match env::var(CONFIG_ENV_VAR) {
        Ok(path) if !path.is_empty() => path,
        _ => panic!("the `tournament` feature requires {CONFIG_ENV_VAR}=configs/<event>.toml"),
    };

    // Re-run only when the named tournament config changes.
    println!("cargo:rerun-if-changed={config_path}");

    let generated = generate_tournament_consts(&config_path);

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by Cargo for build scripts");
    let dest = Path::new(&out_dir).join("tournament_consts.rs");
    fs::write(&dest, generated).unwrap_or_else(|e| panic!("failed to write generated consts to {}: {e}", dest.display()));
}

/// Parse the tournament TOML at `config_path` and render the generated Rust source (malformed config panics).
fn generate_tournament_consts(config_path: &str) -> String {
    let text = fs::read_to_string(config_path).unwrap_or_else(|e| panic!("failed to read tournament config {config_path}: {e}"));
    let table: toml::Table = text
        .parse()
        .unwrap_or_else(|e| panic!("failed to parse tournament config {config_path} as TOML: {e}"));

    // Each entry: TOML key -> generated const name. i32 to match the eval/search hot-path types.
    let fv_scale = required_i32(&table, "fv_scale", config_path);
    let max_moves_to_draw = required_i32(&table, "max_moves_to_draw", config_path);

    format!(
        "// @generated by build.rs from {config_path} — do not edit.\n\
         /// NNUE evaluation scale baked from the tournament config (eval hot path).\n\
         pub const FV_SCALE: i32 = {fv_scale};\n\
         /// Maximum-moves draw horizon (game plies) baked from the tournament config.\n\
         pub const MAX_MOVES_TO_DRAW: i32 = {max_moves_to_draw};\n",
    )
}

/// Fetch an integer key that must be present and fit in `i32`.
fn required_i32(table: &toml::Table, key: &str, config_path: &str) -> i32 {
    let value = table
        .get(key)
        .unwrap_or_else(|| panic!("tournament config {config_path} is missing required key `{key}`"));
    let n = value
        .as_integer()
        .unwrap_or_else(|| panic!("tournament config {config_path} key `{key}` must be an integer, got {value}"));
    i32::try_from(n).unwrap_or_else(|_| panic!("tournament config {config_path} key `{key}` = {n} does not fit in i32"))
}
