//! The engine's settings, compiled in — the search layer's copy.
//!
//! Generated by this crate's `build.rs` from the same TOML config the rest of
//! the engine is built from, and included verbatim below. Nothing here is
//! hand-written, and no value can change at run time.
//!
//! The search reads the handful of keys that shape a node — the draw horizon,
//! the per-colour draw contempt, the non-promotion widening and the
//! entering-king rule. The rest are allowed-but-unused rather than filtered out,
//! so this file cannot drift from the protocol crate's copy.

#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/engine_config.rs"));
