//! The engine's settings, compiled in.
//!
//! Every constant here is generated by this crate's `build.rs` from one TOML
//! config file — `configs/default.toml` unless the `YORKIE_CONFIG` environment
//! variable named another one at build time. Rebuilding is the only way to
//! change a setting.
//!
//! The constants are `pub` so a test can use them in a `const` context and a
//! tool can report what a binary was built with. Engine code goes through
//! `crate::settings::Settings` instead.
//!
//! A constant is its TOML key upper-cased, and its doc comment names the USI
//! option it replaces.

include!(concat!(env!("OUT_DIR"), "/engine_config.rs"));

// A `const` item's initializer is evaluated by the compiler, so these
// assertions could not be written against a value read at run time — they are
// compile-time proof that these really are constants. They also hold the
// structural invariants the engine relies on, even if a future schema edit
// loosens the build script's range checks.
const _: () = assert!(USI_HASH >= 1, "USI_HASH must be at least 1 MiB");
const _: () = assert!(THREADS >= 1, "THREADS must be at least 1");
const _: () = assert!(MULTI_PV >= 1, "MULTI_PV must be at least 1");
const _: () = assert!(BOOK_PV_MOVES >= 1, "BOOK_PV_MOVES must be at least 1");
const _: () = assert!(
    MINIMUM_THINKING_TIME >= 1,
    "MINIMUM_THINKING_TIME must be at least 1 ms"
);
const _: () = assert!(SLOW_MOVER >= 1, "SLOW_MOVER is a percentage, never 0");
const _: () = assert!(!EVAL_DIR.is_empty(), "EVAL_DIR must name a directory");
const _: () = assert!(!BOOK_DIR.is_empty(), "BOOK_DIR must name a directory");
const _: () = assert!(!NUMA_POLICY.is_empty(), "NUMA_POLICY must name a policy");
