//! The engine's settings, compiled in.
//!
//! Every constant here is generated by this crate's `build.rs` from one TOML
//! config file — `configs/default.toml` unless the `YORKIE_CONFIG` environment
//! variable named another one at build time. The generated file is included
//! verbatim below; nothing in this module is hand-written, and there is no way
//! to change a value at run time. Rebuilding is the only way to change a
//! setting.
//!
//! The constants are `pub` so a test can use them in a `const` context and prove
//! they really are compile-time values (see `tests/compile_time_config.rs`), and
//! so a tool can report what a binary was built with. Engine code does not read
//! them directly: it goes through `crate::settings::Settings`, the one place
//! that says where a setting's value comes from.
//!
//! Naming: a constant is its TOML key upper-cased, and its doc comment names the
//! USI option it replaces.

include!(concat!(env!("OUT_DIR"), "/engine_config.rs"));

// Compile-time proof that these are constants, not values fetched at startup: a
// `const` item's initializer is evaluated by the compiler, so none of the
// assertions below could even be written against something read at run time.
// They double as the structural invariants the engine relies on — a worker pool
// of zero threads or a zero-MiB table is not a configuration, it is a crash
// waiting for the first `go`. The build script already range-checks every value;
// these hold even if a future schema edit loosens a bound.
const _: () = assert!(USI_HASH >= 1, "USI_HASH must be at least 1 MiB");
const _: () = assert!(THREADS >= 1, "THREADS must be at least 1");
const _: () = assert!(MULTI_PV >= 1, "MULTI_PV must be at least 1");
const _: () = assert!(BOOK_PV_MOVES >= 1, "BOOK_PV_MOVES must be at least 1");
const _: () = assert!(
    MINIMUM_THINKING_TIME >= 1,
    "MINIMUM_THINKING_TIME must be at least 1 ms"
);
const _: () = assert!(SLOW_MOVER >= 1, "SLOW_MOVER is a percentage, never 0");
const _: () = assert!(!EVAL_DIR.is_empty(), "EVAL_DIR must name a directory");
const _: () = assert!(!BOOK_DIR.is_empty(), "BOOK_DIR must name a directory");
const _: () = assert!(!NUMA_POLICY.is_empty(), "NUMA_POLICY must name a policy");
