//! The engine's settings, compiled in — the storage layer's copy.
//!
//! Generated by this crate's `build.rs` from the same TOML config the rest of
//! the engine is built from, and included verbatim below. Nothing here is
//! hand-written, and no value can change at run time.
//!
//! The storage layer reads exactly one key, `usi_hash`: the transposition
//! table's size, which is an array length here and so has to be a constant. The
//! rest are allowed-but-unused rather than filtered out, so this file cannot
//! drift from the protocol crate's copy.

#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/engine_config.rs"));
